---
- name: Resgata a versão do site atual
  uri:
    url: http://{{ inventory_hostname }}/VERSAO.txt
    status: 200
    return_content: yes
  register: actual_version
  delegate_to: 127.0.0.1

- name: Falha se versão não for a esperada
  fail:
    msg: "A versão em deploy é diferente da esperada. {{ actual_version.content |trim }} != {{ site_version }}"
  when: (actual_version.content | trim) != site_version

